---

- hosts: headsets

  tasks:

    - name: Stop Camera service
      shell:
        cmd: systemctl stop camera.service

    - name: Copy Camera Service
      shell:
        cmd: cp /home/pi/build/2038-AugmentedNormalcy/system/camera.service /etc/systemd/system/

    - name: Copy Camera flip boot config
      shell:
        cmd: cp /home/pi/build/2038-AugmentedNormalcy/system/camera.boot_config.txt /boot/config.txt

    - name: Remove old build dir
      file:
        path: /home/pi/build/2038-AugmentedNormalcy/build
        state: absent

    - name: Remove old binary
      file:
        path: /home/pi/build/2038-AugmentedNormalcy/bin/app_camera
        state: absent

    - name: Create Normalcy build dir
      become: yes
      become_user: pi
      file:
        path: /home/pi/build/2038-AugmentedNormalcy/build
        state: directory
        mode: '0755'

    - name: Setup Normalcy
      become: yes
      become_user: pi
      shell:
        chdir: /home/pi/build/2038-AugmentedNormalcy/build
        cmd: cmake -DAN_PLATFORM:STRING=RPI_CAMERA ..

    - name: Make Normalcy
      become: yes
      become_user: pi
      make:
        chdir: /home/pi/build/2038-AugmentedNormalcy/build
        params:
          NUM_THREADS: 4

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d%H-%M-%S"
      register: tstamp

    - name: Set variables
      set_fact:
        cur_date: "{{ tstamp.stdout[0:10]}}"
        cur_time: "{{ tstamp.stdout[10:]}}"

    - name: System timestamp - date
      debug:
        msg: "Current date: {{ cur_date }}"

    - name: System timestamp - time
      debug:
        msg: "Current date: {{ cur_time }}"
...