---
- hosts: all
  tasks:

    - name: Create a file named /tmp/hello_ansible
      file:
        path: /tmp/hello_ansible
        state: touch

    - name:  Create a file named /tmp/hello_ansible_cameras
      become: yes
      become_user: pi
      file:
        path: /tmp/hello_ansible_cameras
        state: touch
      when: "'cameras' in group_names"

    - name:  Create a file named /tmp/hello_ansible_headsets
      become: yes
      become_user: pi
      file:
        path: /tmp/hello_ansible_headsets
        state: touch
      when: "'headsets' in group_names"

    - name: Check internet connectivity
      command: ping -c3 8.8.8.8
      register: result
      ignore_errors: true

    - name: Show result
      debug:
        msg: "Internet connectivity check failed"
      when: result.rc != 0

...
