---

- hosts: 69.4.20.104

  tasks:

    - name: Reset git repository
      become: yes
      become_user: pi
      shell:
        cmd: git -C /home/pi/build/2038-AugmentedNormalcy reset --hard HEAD
        warn: no
      ignore_errors: true

    - name: Pull the latest normalcy; checkout main branch
      become: yes
      become_user: pi
      git:
        repo: https://github.com/polis-interactive/2038-AugmentedNormalcy
        dest: /home/pi/build/2038-AugmentedNormalcy
        version: main
      environment:
        http_proxy: http://69.4.20.10:8888
        https_proxy: http://69.4.20.10:8888

    - name: Copy NTP client config
      shell:
        cmd: cp /home/pi/build/2038-AugmentedNormalcy/system/ntp.client.conf /etc/ntp.conf

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d%H-%M-%S"
      register: tstamp

    - name: Set variables
      set_fact:
        cur_date: "{{ tstamp.stdout[0:10]}}"
        cur_time: "{{ tstamp.stdout[10:]}}"

    - name: System timestamp - date
      debug:
        msg: "Current date: {{ cur_date }}"

    - name: System timestamp - time
      debug:
        msg: "Current date: {{ cur_time }}"
...