---

- hosts: all

  tasks:

    - name: Stop ntp service
      systemd:
        name: ntp
        state: stopped

    - name: Fix ntp hard
      shell: ntpd -gq

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d%H-%M-%S"
      register: tstamp

    - name: Set variables
      set_fact:
        cur_date: "{{ tstamp.stdout[0:10]}}"
        cur_time: "{{ tstamp.stdout[10:]}}"

    - name: System timestamp - date
      debug:
        msg: "Current date: {{ cur_date }}"

    - name: System timestamp - time
      debug:
        msg: "Current date: {{ cur_time }}"
...