---

- hosts: all

  tasks:

    - name: Update
      apt:
        update_cache: yes
      environment:
        http_proxy: http://69.4.20.10:8888
        https_proxy: http://69.4.20.10:8888

    - name: Install PIGPIO
      apt:
        pkg:
          - pigpio
      environment:
        http_proxy: http://69.4.20.10:8888
        https_proxy: http://69.4.20.10:8888

    - name: Pull the latest normalcy; checkout dev branch
      become: yes
      become_user: pi
      git:
        repo: https://github.com/polis-interactive/2038-AugmentedNormalcy
        dest: /home/pi/build/2038-AugmentedNormalcy
        version: bms-gpio-work
      environment:
        http_proxy: http://69.4.20.10:8888
        https_proxy: http://69.4.20.10:8888

    - name: Make Normalcy
      become: yes
      become_user: pi
      make:
        chdir: /home/pi/build/2038-AugmentedNormalcy/build
        params:
          NUM_THREADS: 4

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d%H-%M-%S"
      register: tstamp

    - name: Set variables
      set_fact:
        cur_date: "{{ tstamp.stdout[0:10]}}"
        cur_time: "{{ tstamp.stdout[10:]}}"

    - name: System timestamp - date
      debug:
        msg: "Current date: {{ cur_date }}"

    - name: System timestamp - time
      debug:
        msg: "Current date: {{ cur_time }}"
...