---

- hosts: 69.4.20.100
  environment:
    http_proxy: http://localhost:8080
    https_proxy: http://localhost:8080

  tasks:
    - name: start ssh tunnel
      shell:
        cmd: nohup ssh -N polis@69.4.20.10 -L 8080/localhost/8080 &

    - name: Create a file named /tmp/hello_ansible
      file:
        path: /tmp/hello_ansible
        state: touch

    - name:  Create a file named /tmp/hello_ansible_cameras
      become: yes
      become_user: pi
      file:
        path: /tmp/hello_ansible_cameras
        state: touch
      when: "'cameras' in group_names"

    - name:  Create a file named /tmp/hello_ansible_headsets
      become: yes
      become_user: pi
      file:
        path: /tmp/hello_ansible_headsets
        state: touch
      when: "'headsets' in group_names"

    - name: Update, Upgrade
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        pkg:
          - emacs
...
