---
- hosts: all
  tasks:
    # INSTALL DEPS
    - name: Update, Upgrade
      apt:
        update_cache: yes
        upgrade: dist
    - name: Install dependencies
      apt:
        pkg:
          - vim
          - git
          - tmux
          - arping
          - net-tools
          - ntp
          - build-essential
          - cmake
          - nload
          - libcamera-dev
          - libcamera-apps
          - libjpeg-dev
    # SETUP PI STUFF
    - name: Remove default pi user
      ansible.builtin.user:
        name: pi
        state: absent
    - name: Create a new pi and set password
      ansible.builtin.user:
        name: pi
        password: "{{ 'raspberry' | password_hash('sha512') }}"
        shell: /bin/bash
    - name: Provision WiFi
      copy:
        src: ./camera.wpa_supplicant.conf
        dest: /boot/wpa_supplicant.conf
    - name: Provision SSH
      file:
        path: /boot/ssh
        state: touch
    - name: Setup dhcpcd
      copy:
        src: ./camera.dhcpcd.conf
        dest: /etc/dhcpcd.conf
    - name: Change the Timezone
      shell:
        cmd: raspi-config nonint do_change_timezone America/Chicago
    - name: Change the country
      shell:
        cmd: raspi-config nonint do_change_locale en_US.UTF-8
    - name: Change the keyboard
      shell:
        cmd: raspi-config nonint do_configure_keyboard us
    - name: Change the hostname
      shell:
        cmd: raspi-config nonint do_hostname Camera
    - name: Disable userconfig
      shell:
        cmd: systemctl disable userconfig
    - name: Enable terminal still
      shell:
        cmd: systemctl enable getty@tty1
    - name: Create build dir
      become: yes
      become_user: pi
      file:
        path: /home/pi/build
        state: directory
        mode: '0755'
    # BOOST
    - name: Download Boost
      become: yes
      become_user: pi
      get_url:
        url: https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
        dest: /home/pi/build
      register: BOOST_ARCHIVE
    - name: UnArchive Boost
      become: yes
      become_user: pi
      unarchive:
        src: "{{ BOOST_ARCHIVE.dest }}"
        dest: /home/pi/build
        copy: no
    - name: Setup boost
      become: yes
      become_user: pi
      shell:
        chdir: /home/pi/build/boost_1_81_0
        cmd: ./bootstrap.sh gcc
    - name: Build boost
      become: yes
      become_user: pi
      shell:
        chdir: /home/pi/build/boost_1_81_0
        cmd: ./b2 --with-system --with-thread --with-date_time --with-regex --with-serialization stage
    # NORMALCY
    - name: Download Normalcy
      become: yes
      become_user: pi
      git:
        repo: https://github.com/polis-interactive/2038-AugmentedNormalcy
        dest: /home/pi/build/2038-AugmentedNormalcy
    - name: Create Normalcy build dir
      become: yes
      become_user: pi
      file:
        path: /home/pi/build/2038-AugmentedNormalcy/build
        state: directory
        mode: '0755'
    - name: Setup Normalcy
      become: yes
      become_user: pi
      shell:
        chdir: /home/pi/build/2038-AugmentedNormalcy/build
        cmd: cmake -DAN_PLATFORM:STRING=RPI_CAMERA ..
    - name: Make Normalcy
      become: yes
      become_user: pi
      make:
        chdir: /home/pi/build/2038-AugmentedNormalcy/build
        params:
          NUM_THREADS: 4
    # SYSTEM
    - name: Copy Camera Service
      shell:
        cmd: cp /home/pi/build/2038-AugmentedNormalcy/system/camera.service /etc/systemd/system/
    - name: Copy Restart Service
      shell:
        cmd: cp /home/pi/build/2038-AugmentedNormalcy/system/restart-system.service /etc/systemd/system/
    - name: Reload systemd
      shell:
        cmd: systemctl daemon-reload
    - name: Enable Camera Service
      shell:
        cmd: systemctl enable camera.service
    - name: Copy Cron Reboot
      shell:
        cmd: cp /home/pi/build/2038-AugmentedNormalcy/system/cron-reboot /etc/cron.d/reboot
    - name: Copy NTP client config
      shell:
        cmd: cp /home/pi/build/2038-AugmentedNormalcy/system/ntp.client.conf /etc/ntp.conf
    - name: Copy Camera flip boot config
      shell:
        cmd: cp /home/pi/build/2038-AugmentedNormalcy/system/camera.boot_config.txt /boot/config.txt
    # MANAGEMENT
    - name: Create ssh dir
      become: yes
      become_user: pi
      file:
        path: /home/pi/.ssh
        state: directory
        mode: '0755'
    - name: Copy authorized server key
      shell:
        cmd: cp /home/pi/build/2038-AugmentedNormalcy/management/authorized_keys.client /home/pi/.ssh/authorized_keys