//
// Created by brucegoose on 2/5/23.
//

#ifndef AUGMENTEDNORMALCY_PROTOTYPE_PREPROCESSOR_HPP
#define AUGMENTEDNORMALCY_PROTOTYPE_PREPROCESSOR_HPP

#define PLATFORM_BROOSE_WINDOWS_LAPTOP 1
#define PLATFORM_BROOSE_LINUX_LAPTOP 10
#define PLATFORM_RPI 20
#define PLATFORM_JETSON 30

#endif //AUGMENTEDNORMALCY_PROTOTYPE_PREPROCESSOR_HPP
