if (
    FEATURE_DECODER AND (
        (AN_PLATFORM_TYPE STREQUAL RPI) OR
        (AN_PLATFORM_TYPE STREQUAL LINUX)
    )
)
    set(V4L2_DECODER_AVAILABLE 1)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_V4L2_DECODER_")
endif()