
if (
    (AN_PLATFORM STREQUAL JETSON_CC) OR
        (AN_PLATFORM STREQUAL JETSON) OR
        (AN_PLATFORM STREQUAL BROOSE_LINUX_LAPTOP)
)
    set(FEATURE_ENCODER true)
    set(FEATURE_BUFFER true)
endif()

if (
    (AN_PLATFORM STREQUAL RPI_CAMERA) OR
        (AN_PLATFORM STREQUAL RPI_CAMERA_CC) OR
        (AN_PLATFORM STREQUAL BROOSE_LINUX_LAPTOP)
)
    set(FEATURE_CAMERA true)
endif()
