
if (FEATURE_GRAPHICS)
    set(GLFW3_VERSION 3.3)
    set(GLFW3_LINK_LIBRARIES glfw3 EGL GL dl X11)
    find_package(glfw3 ${GLFW3_VERSION} CONFIG REQUIRED)
    message(STATUS "glfw3 library found:")
    message(STATUS "    version: ${GLFW3_VERSION}")
    message(STATUS "    libraries: ${GLFW3_LINK_LIBRARIES}")
endif()

if (
    (AN_PLATFORM STREQUAL RPI_HEADSET) OR
    (AN_PLATFORM STREQUAL RPI_HEADSET_CC) OR
        AN_PLATFORM_TYPE STREQUAL "LINUX"
)
    set(HEADSET_GRAPHICS_AVAILABLE 1)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_HEADSET_GRAPHICS_")
endif()

if (
    (AN_PLATFORM STREQUAL RPI_DISPLAY) OR
    (AN_PLATFORM STREQUAL RPI_DISPLAY_CC) OR
        AN_PLATFORM_TYPE STREQUAL "LINUX"
)
    set(DISPLAY_GRAPHICS_AVAILABLE 1)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_DISPLAY_GRAPHICS_")
endif()
