
if (NOT DEFINED AN_PLATFORM)
    message(FATAL_ERROR "AN_PLATFORM unset" )
elseif (
    NOT AN_PLATFORM STREQUAL JETSON
    AND NOT AN_PLATFORM STREQUAL JETSON_CC
    AND NOT AN_PLATFORM STREQUAL RPI_CAMERA
    AND NOT AN_PLATFORM STREQUAL RPI_CAMERA_CC
    AND NOT AN_PLATFORM STREQUAL RPI_HEADSET
    AND NOT AN_PLATFORM STREQUAL RPI_HEADSET_CC
    AND NOT AN_PLATFORM STREQUAL BROOSE_LINUX_LAPTOP
)
    message(FATAL_ERROR "Unhandled AN_PLATFORM: ${AN_PLATFORM}" )
endif()
