
if (NOT DEFINED AN_PLATFORM)
    message(FATAL_ERROR "AN_PLATFORM unset" )
elseif (
    NOT AN_PLATFORM STREQUAL JETSON
    AND NOT AN_PLATFORM STREQUAL JETSON_CC
    AND NOT AN_PLATFORM STREQUAL RPI_CAMERA
    AND NOT AN_PLATFORM STREQUAL RPI_CAMERA_CC
    AND NOT AN_PLATFORM STREQUAL RPI_HEADSET
    AND NOT AN_PLATFORM STREQUAL RPI_HEADSET_CC
    AND NOT AN_PLATFORM STREQUAL BROOSE_LINUX_LAPTOP
)
    message(FATAL_ERROR "Unhandled AN_PLATFORM: ${AN_PLATFORM}" )
else()
    if (
        AN_PLATFORM STREQUAL JETSON
        OR AN_PLATFORM STREQUAL JETSON_CC
    )
        set(AN_PLATFORM_NUM 30)
        set(AN_PLATFORM_TYPE JETSON)
    elseif (
        AN_PLATFORM STREQUAL RPI_CAMERA
        OR AN_PLATFORM STREQUAL RPI_CAMERA_CC
        OR AN_PLATFORM STREQUAL RPI_HEADSET
        OR AN_PLATFORM STREQUAL RPI_HEADSET_CC
    )
        set(AN_PLATFORM_NUM 20)
        set(AN_PLATFORM_TYPE RPI)
    else()
        set(AN_PLATFORM_NUM 10)
        set(AN_PLATFORM_TYPE LINUX)
    endif()

    message("Using host: ${AN_PLATFORM}")
    message("Using platform: ${AN_PLATFORM_TYPE}")
    message("Using platform number: ${AN_PLATFORM_NUM}")

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DPLATFORM_BROOSE_WINDOWS_LAPTOP=1")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DPLATFORM_BROOSE_LINUX_LAPTOP=10")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DPLATFORM_RPI=20")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DPLATFORM_JETSON=30")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_AN_PLATFORM_=${AN_PLATFORM_NUM}")
endif()
